[package]
name = "policy-worker"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
aws-sdk-s3.workspace = true
chrono.workspace = true
policy-shared = { path = "../shared" }
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true
